# supported: phone, smart display (partial)
triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: basic_card
states:
    # meya.text is required before meya.card
    basic_card_0:
        component: meya.text
        properties:
            text: This is a basic card example.
    basic_card_1:
        component: meya.card
        properties:
            title: Basic card title
            subtitle: Basic card subtitle
            text: "Formatted text goes here"
            image_url: "https://upload.wikimedia.org/wikipedia/commons/7/71/2010-kodiak-bear-1.jpg"
            output: button_click
            # required if no buttons are specified
            passthru: true
            expect_user_action: false
