# supported: phone, smart display (partial)
triggers:
  - type: meya.keyword
    properties:
        ignorecase: true
        keyword: image
states:
    # meya.text is required before meya.image
    basic_card_0:
        component: meya.text
        properties:
            text: This is an image example.
    basic_card_1:
        component: meya.image
        properties:
            image_url: "https://upload.wikimedia.org/wikipedia/commons/c/c1/Lionel_Messi_20180626.jpg"
            accessibility_text: "Messi photo" # optional
            image_display_options: "WHITE" # optional
