triggers:
  - type: meya.start_voice_chat
intents:
    # change this value to change the default behavior of the bot
    start: choose
states:
    choose:
        component: meya.text_suggestions
        properties:
            text:
                Welcome to Meya's Google Assistant demo.
                Make a choice of what you'd like to see.
            suggestions:
                - Basic card
                - Suggestion chips
                - Browsing carousel
                - Media responses
                - Table cards
                - List
                - Carousel
        transitions:
            Basic card: basic_card_buttons
            Suggestion chips: text_buttons
            Browsing carousel: browsing_carousel
            Media responses: audio
            Table cards: table_buttons
            List: list
            Carousel: carousel
    simple_response:
        flow: simple_response
        return: true
    basic_card:
        flow: basic_card
        return: true
    basic_card_buttons:
        flow: basic_card_buttons
        return: true
    text_suggestions:
        flow: text_suggestions
        return: true
    text_buttons:
        flow: text_buttons
        return: true
    image_buttons:
        flow: image_buttons
        return: true
    image:
        flow: image
        return: true
    browsing_carousel:
        flow: browsing_carousel
        return: true
    audio:
        flow: audio
        return: true
    table:
        flow: table
        return: true
    table_buttons:
        flow: table_buttons
        return: true
    list:
        flow: list
        return: true
    carousel:
        flow: carousel
        return: true